### PR TITLE
Rangy official

### PR DESCRIPTION
**Pull request by plumpNation**
rangy was not found by bower and this looks kind of important for the build and deployment. rangy-official seems to be the correct bower repo name now, and all the tests passed on build.

### CODE REVIEW

**Comment by muratcorlu** [comment]
When this will be versioned?

**Comment by ddeboer** [comment]
:+1:

**Comment by zpengyu** [comment]
:+1:

**Comment by plumpNation** [comment]
@muratcorlu apologies, are you asking me 'when will this be versioned?'.

If so, I'm sorry but I don't know exactly what you mean. Happy to oblige once I know.

**Comment by muratcorlu** [comment]
I mean, our textangular dependencies are broken now, so I wonder, when will this fix be released and we can download a fixed version of textangular with bower.

**Comment by mrfelton** [comment]
textAngular-rangy.min.js needs to be regenerated too.

**Comment by SimeonC** [comment]
Ugh, that's just horrid when people decide to remove bower packages. I was waiting till they officially released 1.3.0, but I guess I have not much choice at this point!! Thanks for the PR, I'll get it merged in ASAP.

**Comment by SimeonC** [comment]
Merged, and v1.3.0 released!

**Comment by muratcorlu** [comment]
Thanks for the fast response :clap:

**Comment by plumpNation** [comment]
Awesome. Thanks!

**Comment by ddeboer** [comment]
Yeah!

**Comment by muratcorlu** [comment]
Bad news: https://github.com/timdown/rangy-release/commit/b0841582876035240fb98f70065c5fae124b97c2

**Comment by SimeonC** [comment]
Ugh. Who would have known it could be a bad thing to update quickly!
I'll get it patched out again...

**Comment by plumpNation** [comment]
oh dear :)

**Comment by SimeonC** [comment]
I patched it in v1.3.1, again. We should be all good now!!

**Pull request merged**
