### PR TITLE
Cleanup event handlers that are placed on the window

### PR DESCRIPTION
**Pull request by blittle**
If these aren't cleaned up:
1. They are a memory leak
2. Some versions of Internet Explorer throw errors when you load textAngular, then unload it, then start scrolling.

### CODE REVIEW

**Comment by fcaballero** [comment]
Hi,

May someone merge this change?

**Comment by fcaballero** [comment]
Hi @JoelParke, any chance to merge this, it's introducing memory leaks on IE, every time I open a view which contains textangular (almost all), the scope of the view is keep in memory, after 5-10 minutes using the web app, IE crashes because it's running out of memory.
So please, may you take care of merging this changes?

**Comment by pabloes** [comment]
please, merge the PR, the issue is important.

**Comment by JoelParke** [comment]
<p>I will try and get to this late today??? Thanks for reporting this issue.</p>

**Comment by fcaballero** [comment]
Thanks, @JoelParke ;)

**Pull request merged**
