### PR TITLE
fix(taBind): fix for #944

### PR DESCRIPTION
**Pull request by JoelParke**
This fix partially may break the fix by yaldak.
I am asking him to check this change... 

Fix: #944

### CODE REVIEW

**Comment by yaldak** [comment]
No problem, I will take a look

**Comment by yaldak** [comment]
So, this causes newline pasting on Linux (LF) to no longer work again.

I do not have a Windows machine available at this time but I will later in the day to see if I can revise this fix.

I think I know how, I just have to try it.

Thank you

**Comment by yaldak** [comment]
Sorry - I should have given Windows some more attention in the first place. I generally stay in Linux territory .

**Comment by JoelParke** [comment]
Not a problem... I too don't spend much time on Windows :-) anymore.   When I looked at the error, I guessed that it just needed to only do the /n /r --> <br/> within the body of the <html><...fragment> ...do the substitutions here... </...fragment></html>   ETC...

**Comment by pbassut** [comment]
Is this supposed to be merged then?

**Comment by JoelParke** [comment]
I had assumed that yaldak would improve my fix slightly to handle the case on windows so that the piece I removed could be enabled again.  But that didn't happen yet... so I will take a look an fix that soon and amend the pull request to take care of that.

**Comment by pbassut** [comment]
You're on Mac, right? https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/

**Comment by cboe** [comment]
I have noticed the same issue on chrome on mac os x

**Comment by JoelParke** [comment]
No, primarily Ubuntu, but I have a windows 7 virtual machine I bring up.

**Comment by yaldak** [comment]
Sorry everyone, have been out sick! I will work on this tonight.

**Comment by JoelParke** [comment]
Sorry to hear you have been sick! Glad you are better, and I have been busy
with some other stuff and so haven't done anything on this.

**Comment by pbassut** [comment]
I figure this out and will provide a new PR since Joel removed support for other new-lines.
It's easy. Tomorrow night I'll get this done.

**Pull request closed without merging**
