### PR TITLE
fix(placeholder):cssRuleIndex will change if there are multiple textAngu...

### PR DESCRIPTION
**Pull request by kaiqigong**
...lar in one page, so that removeCSSRule(ruleIndex) will cause error

### CODE REVIEW

**Comment by kaiqigong** [comment]
commit for #568

**Comment by SimeonC** [comment]
Thanks for the PR, there's two problems though.

1. Your edits should be done in the `lib/globals.js` file.
2. I'm a little concerned that I cannot find any reference to being able to remove a rule by object reference. As far as I can see you have to remove a rule by index, can you provide references please? (A possible workaround may be to use `indexOf(rule)` to get the index.

**Comment by kaiqigong** [comment]
@SimeonC ,
1. Right, my local version is quite out of dated. I will make another PR.
2. I tried this "remove by object reference" in latest chrome/firefox and it works. But since this feature cannot be found documented anywhere. So I guess I should follow your suggestion. :smile:

**Comment by SimeonC** [comment]
Awesome thanks, I'll patch this in as soon as I can.

**Comment by SimeonC** [comment]
In release v1.3.10

**Pull request merged**
