### PR TITLE
fixing issue #606

### PR DESCRIPTION
**Pull request by Hike-zzz**
previos fix no more needed

### CODE REVIEW

**Comment by pbassut** [comment]
Did you test it on a webkit browser? (E.g. Safari)

**Comment by Hike-zzz** [comment]
Yes. Opera and Chromium in Ubuntu 14.04.

**Comment by pbassut** [comment]
Those are blink based browser. Not webkit.

**Comment by Hike-zzz** [comment]
I'll check...

**Comment by Hike-zzz** [comment]
All good in safari.

**Pull request merged**
