### PR TITLE
feature(textAngular): Fixed aspect ratio option for images resize

### PR DESCRIPTION
**Pull request by nickknissen**
Create option for text-angular which makes it possible to lock aspect
ration for image resize. The option is "ta-image-resize-aspect-ratio"

### CODE REVIEW

**Comment by nickknissen** [comment]
Note that https://github.com/fraywing/textAngular/wiki/Directives should be updated if this is merged.

**Comment by JoelParke** [comment]
I like this idea Nick... but I noticed in testing that when you enable this, the fixed ratio collides with the popup that handles the 25%, 50%, 100% ... so there needs to be a corresponding fix there as well.

**Comment by nickknissen** [comment]
I will look into that

**Comment by nickknissen** [comment]
#775 fixes mixing popup button and resize handle.

**Comment by JoelParke** [comment]
Oh -- if I had just looked a bit further!  So nice that this with #775 greatly improve!

**Comment by JoelParke** [comment]
After having merged this -- I thought began to wonder if we should use this option to JUST flip the function of the shiftKey?  I.E. one could use the shiftKey to break the fixed aspect ratio when this option is engaged. -

Or do you think it is better to force the aspect ratio to be locked?

**Comment by nickknissen** [comment]
I can create a new MR with something like `ta-image-resize-flip-aspect-ratio-keybinding`

**Comment by JoelParke** [comment]
if you pull the current HEAD -- that's a good place to start... so we stay in sync :-)
ta-image-resize-flip-aspect-ratio-keybinding sounds good.

**Comment by pbassut** [comment]
Can't we make this directive shorter but still preserve the meaning?

**Comment by JoelParke** [comment]
I like short as well, but it's a style thing and Nick is doing the work... so do you have a suggestion for Nick?

**Comment by pbassut** [comment]
@JoelParke No, sorry. Just wanted to point this out. =/

**Comment by nickknissen** [comment]
I could do something different.  
`ta-resize-force-aspect-ratio`(renamed from `ta-image-resize-keep-aspect-ratio`)  
`ta-resize-maintain-aspect-ratio` (`false` as default and used to flip the aspect ratio keybinding)

**Comment by pbassut** [comment]
@nickknissen That's much better! Thanks!

**Comment by JoelParke** [comment]
I like these... I think for the upcoming release, I will add these directly so that the documentation doesn't need to be done twice.

**Pull request merged**
