### PR TITLE
Fixed typo.

### PR DESCRIPTION
**Pull request by Tomegreene**
Fixed a typo on a tooltip.

### CODE REVIEW

**Comment by SimeonC** [comment]
Thanks for spotting that. I'll get it in once I figure out what's wrong with TravisCI...

**Comment by Tomegreene** [comment]
No problem, though it was actually someone using a page that included textAngular and I had to debug where the tooltip came from. Figured it was an easy enough fix to hand off to you, and save you some time.

**Comment by Tomegreene** [comment]
Did travis get fixed in order to pull in the typo fix?

**Comment by SimeonC** [comment]
Yea, Sorry been rather busy and forgot to rerun the tests.

**Comment by Tomegreene** [comment]
No problem and thanks.

**Pull request merged**
