### PR TITLE
Fixed the tooltip in Strikethrough and added comments to readme

### PR DESCRIPTION
**Pull request by Percussionista**
Added the tooltiptext to the strikethrough tool and added some comments to the readme to give a better idea where to look when needing to customize the toolbar. This section could stand to be fleshed out by someone more knowledgeable than me.

I also fixed the wordcount action function to not freak out when markup is added within a word. I added some unit tests to ensure that the counts are still correct.

### CODE REVIEW

**Comment by Percussionista** [comment]
The Travis build is failing due to not having 100% coverage, which is odd since I actually added another test. Any ideas?

**Comment by SimeonC** [comment]
It says branches, which means if statements - I'd hazard it's this line: https://github.com/fraywing/textAngular/pull/597/files#diff-cbd86781c5c78226e7a486a23a97a0e2R663.

Basically the right side of the `||` doesn't get tested - i.e. no content. If you want you can just add an coverage ignore else for that line.

**Comment by Percussionista** [comment]
Finally! Thanks, SimeonC.

**Comment by Percussionista** [comment]
One of the changes I made in this set of pull requests was to the readme file. I added a blurb about customizing the toolbar, which I needed to do for my use case. It took forever to figure out what I was doing and I ended up reading the comments in the demo to try to piece together how to do it. Silly me - I didn't realize the information I needed was mostly in the wiki. If it would speed up my pull request, I am open to removing the changes to the readme file, but I think there should at least be a note pointing users to the wiki for customization information. Thanks!

**Comment by SimeonC** [comment]
Hey, sorry about the delay - I'm in the middle of changing jobs (2 weeks left!) which doesn't allow me a lot of time for much apart from responding to issues. As soon as I have the time I work through getting PR's merged first then working on some of the outstanding bugs.

**Comment by Percussionista** [comment]
No problem. Congrats and good luck on the new job! You're doing a great job with the project. Thanks!

**Comment by SimeonC** [comment]
This is merged, though I seemed to have stuffed up something and it's not being marked as such.

**Pull request closed without merging**
