### PR TITLE
added aria-hidden to hidden input, to hide it from screen readers

### PR DESCRIPTION
**Pull request by CameronAM**

### CODE REVIEW

**Comment by pbassut** [comment]
I think the title of this should be changed to conform to the [guidelines](https://github.com/fraywing/textAngular/blob/master/CONTRIBUTING.md)

**Comment by JoelParke** [comment]
I did the right sort of title .... fix(globals.js): added aria-hidden to hidden input, to hide it from screen readers
but the gitHub merge only seems to put that after the head title of 'Merged pull request #xxx ...' 
This seems too bad, since it means that unless the title of the pull request is exactly right, we have to redo the merge.  Yuck.

**Comment by pbassut** [comment]
Yeah, you're right. I noticed it. Well, this one aside then.

**Comment by JoelParke** [comment]
It almost seems that we should make the release tool a bit smarter and have it pull out the titles -- not sure how easy or worth while that might be... but I will think about it.  I suspect that after we get though a couple of release cycles this will get easier :-)

**Pull request merged**
