### PR TITLE
fix for polish programmers keyboard alt+z 

### PR DESCRIPTION
**Pull request by akupiec**
Fix for bug mentioned here fraywing/textAngular#518

### CODE REVIEW

**Comment by SimeonC** [comment]
Thanks for the fix, I'll have to check this through as it seems some of my tests using ctrl don't work.

**Comment by akupiec** [comment]
I ran your tests (grunt karma) on my local machine and they all passed without problems, so I can't do much about it.

**Comment by SimeonC** [comment]
Did you run just `grunt karma` or the just `grunt`? You should just run the default grunt task that then compiles everything up before the tests. (You can see the tests run by travis here https://travis-ci.org/fraywing/textAngular/builds/54745052)

Don't worry about it this time, I know the issue and can fix it up, it'll just take me a bit to get some time to do it as I'm starting a new job soon so chaos reigns at the moment!

**Comment by SimeonC** [comment]
Having a look at it, I think your code will actually break things as in the case of CTRL+Z the ctrl flag will be false as the keycode will be for ctrl or z not both we can't undo by key command.

I think the correct fix is this: `if(!event.altKey && (event.metaKey || ctrlKey)){` which I got from [here](https://github.com/xing/wysihtml5/commit/4728930ce816ca498f63e1f958bdf22787989c9d) - I think last time I didn't bracket correctly.

I've also added in a test to check this time - Triggering Alt + Ctrl + Z doesn't fire the undo command now which from what I understand is the problem. Can you grab the version from master and confirm this please?

**Comment by akupiec** [comment]
@SimeonC 
Thank you very much, ctrl+z as well polish "ż" works now fine.
Please don't forget about release ^_^

**Comment by SimeonC** [comment]
Awesome, thanks for confirming it - I couldn't myself.

**Pull request merged**
