### PR TITLE
Adapted for MaterializeCSS

### PR DESCRIPTION
**Pull request by DavidBernal**
In this branch you can use MaterializeCSS with Material Design icons instead of Bootstrap.

### CODE REVIEW

**Comment by pbassut** [comment]
Do you think this should be merged? Why change bootstrap to material design?

**Comment by DavidBernal** [comment]
Because not everybody use bootstrap.
For example (real), I have a project with materializeCSS, and need your plugin. I have 3 possibilities, use bootstrap + materializeCSS (conflicts, more Mb.), change materializeCSS for bootstrap (a lot of work) or adapt your plugin for materializeCSS. I choose the third option, and I think someone else can use.

You choose. I've my problem solved.

Greetings.

**Comment by JoelParke** [comment]
I haven't had a chance to yet look at this Patrick.  I will attempt to do so in a week or so...   In general I think the material design (Google android) stuff is good, but it is mostly cosmetic.  Even so, to support it, if it is not hard is a good idea.  So we will see....

**Comment by pbassut** [comment]
Check out @SimeonC's comment on this issue: https://github.com/fraywing/textAngular/issues/625#issuecomment-138380833

**Comment by Cayan** [comment]
@JoelParke Material is a concept.
There are a lot of different implementations of it, in my case I use angular material and I've seen some issues/PR's open about it.

This pull request breaks bootstrap compatibility.
IMO a better approach would be using templates.

**Pull request closed without merging**
