### PR TITLE
Fix(taBind): selection unexpected change in click toolbar button

### PR DESCRIPTION
**Pull request by raffy2010**

### CODE REVIEW

**Comment by pbassut** [comment]
What issue does this PR fixes?

**Comment by raffy2010** [comment]
little hard to describe that issue, I have recorded a video to illustrate it.

It maybe caused by i element inside the button

Alt Text

**Comment by pbassut** [comment]
Does the issue only shows up on chrome? Does it happen on firefox too?

**Comment by raffy2010** [comment]
It's ok in Firefox, looks like chrome has the problem(not test in edge yet)
but many actions like insert link, insert image and quote does not work correctly just like insert video.


I will create an issue to discuss this problem.
thank you 😄

**Comment by gbittmann** [comment]
Is this related to https://github.com/fraywing/textAngular/pull/1216 ? I watched the video and it looks like you're switching the focus in and out of textAngular which is an issue in Chrome / Safari currently.

**Comment by pbassut** [comment]
@gbittmann That's interesting. One issue might exclude the other. We need to check that first.

**Comment by gbittmann** [comment]
From the video it looks like: 
focus in, 
focus out, 
focus in,
click insert image URL, doesn't work.

Which is the same pattern just in this case reported for one button instead of the entire toolbar.

I saw the same behavior in Edge also using testangular.com. 
It works fine in IE 11.

**Comment by JoelParke** [comment]
I can no longer reporduce with with v1.5.8.  Please reopen and create a plunkr if still an issue.  Thanks!

**Pull request closed without merging**
