### PR TITLE
fix 644: parse whitespace from plaintext

### PR DESCRIPTION
**Pull request by yaldak**
Hello,

Attached is the most recent version of pull request 644. Sorry for the drag in getting this ready.
Please let me know if there is anything I can do.

Regards,
Yalda

### CODE REVIEW

**Comment by pbassut** [comment]
Now the last thing I need is a rebase :)

**Comment by pbassut** [comment]
Also, do you know if that closes any other issues? If so, can you point them out?

**Comment by yaldak** [comment]
I'll look for other issues.

I admittedly don't know how to do the rebase you are asking for :(

**Comment by yaldak** [comment]
This should also fix https://github.com/fraywing/textAngular/issues/786

I do not have Office to test as I am in a Linux shop, but I will see what I can do.

**Comment by pbassut** [comment]
No need for the rebase then. I already asked too much. Thanks for your PR ;p

**Comment by yaldak** [comment]
My pleasure.

Thank you, Patrick.

**Comment by JoelParke** [comment]
yaldak can you take a look at pr #945 where I needed to break part of this fix... 
Please let me know if what I did breaks part of your issue here...

**Pull request merged**
