### PR TITLE
Fix(taBind): Reapply selector handles on focus

### LINKED ISSUE #777: Images doesn't get toolbar when content is loaded asyc
Images doesn't get a toolbar when clicked if the content is loaded async or delayed.
You have to write something before before the images can be clicked and the toolbar is shown

This seems to be an issue across all browsers and all angular versions
Se this branch for a demo of the issue: https://github.com/educas/textAngular/tree/demo-no-image-toolbar-with-async-data

### PR DESCRIPTION
**Pull request by nickknissen**
This fixes image overlay not responding until some edit operation has been performed.
Fixes #777

### CODE REVIEW

**Comment by pbassut** [comment]
Looks like it broke some tests due something you did with taBind. Mind looking into it?

**Comment by nickknissen** [comment]
Sure thing

**Comment by nickknissen** [comment]
Fixed
Instead of using `scope.updateTaBindtaTextElement`  on `textAngular` directive i used `_reApplyOnSelectorHandlers` which was accessible inside `taBind` directive.

**Comment by episodeyang** [comment]
Looks good to me!

**Pull request merged**
