### PR TITLE
Ignore INDEX_SIZE_ERR error that occurs when selection is empty

### PR DESCRIPTION
**Pull request by jooohn**
INDEX_SIZE_ERR sometimes occurs when I type any characters in text-angular element, and open a bootstrap modal window immediately.

### CODE REVIEW

**Comment by shuhei** [comment]
@pbassut Is this PR OK to merge? The error happens pretty often on our production app...

**Comment by shuhei** [comment]
The CI's errors don't seem to be caused by this PR.

**Comment by pbassut** [comment]
The CI's error was fixed. If you rebase your changes on top of the current master, this would get fixed. 
Let me first know if the issue really exists and it's worth merging your pr. Then you can get it in able to merge state 

Enviado do meu iPhone

**Comment by pbassut** [comment]
Looks like this can be merge now. I'll review it when I get home and merge if everything is okay.

**Comment by pbassut** [comment]
As I see it, this can't be merged. Just making the error quiet is not a very good fix. 
Why is the error raised in the first place?
What can be done to fix it?
Wrapping the code that's not working in a try-catch block is not good.

**Comment by jooohn** [comment]
@pbassut 

Thanks for reviewing.

`taSelection.getSelectionElement` might throw a DOM Exception "INDEX_SIZE_ERR", from here (https://github.com/fraywing/textAngular/blob/master/src/DOM.js#L257). It occurs when range for selection is empty (https://github.com/timdown/rangy/blob/master/src/core/wrappedselection.js#L606), and because it might be thrown in `$timeout` function, we cannot handle it easily.

`rangy.getSelection().getRangeAt(0)` is called some places, so I followed this style (https://github.com/fraywing/textAngular/blob/master/src/DOM.js#L40-42). I don't think try-catch is the best solution, but I think it's better than throwing an exception which is difficult to handle.

but what do you think?

**Pull request closed without merging**
