### PR TITLE
correct behavior for indent and outdent and enter inside lists on "keydown"

### PR DESCRIPTION
**Pull request by episodeyang**
I had a hard time coming up with the tests, but the code itself should be pretty good this time. It is completely re-written.

Since this part of the code would be interesting to a lot of people, I would like to help merge it into the main repo. The code is written as bunch of functions with minimal interference and dependence on existing logic inside the `taExecCommand` directive.

### CODE REVIEW

**Comment by episodeyang** [comment]
I moved the changed to the correct file `lib/DOM.js` 

Still need to take care of the test at some point. Sorry about this delay!

**Comment by SimeonC** [comment]
Looks good, I'll get onto this once I've cleared my backlog.

**Comment by SimeonC** [comment]
Ok, on review I'm going to push this out to 1.3.1, as it's a bit big, but I do like what you've done with the tab and backspace stuff with the indent. Just as a note - It's best to remove all the console.log's before submitting a pr.

**Comment by episodeyang** [comment]
Thanks @Simeon,

Sorry about the console.log. It is definitely something I should remove
before submitting!

I am working on an enhanced version of this pull-request. I will submit it
on top of this and squash them.

Ge

**Comment by JoelParke** [comment]
I believe this was merged long ago.. so closing.

**Pull request closed without merging**
