### PR TITLE
Fix dependency issue with textAngularSetup to allow use of constant taRegisterTool

### PR DESCRIPTION
**Pull request by garhbod**
Fix issue #608

### CODE REVIEW

**Comment by pbassut** [comment]
Wouldn't this generate a circular dependency issue?

**Comment by garhbod** [comment]
Yes but it is a usable solution for those who run into the problem I did. Why is textAngularSetup even seperated from the main textAngular module?
If the dependency is circular and as far as I can see nothing else is dependent on textAngularSetup why aren't they combined?

**Comment by toxaq** [comment]
Got here via the ocLazyLoader issue and this resolves it for me. I don't really understand why textAngularSetup is in a seperate file and why textangular.min.js is not a min version of textangular.js

**Comment by garhbod** [comment]
That's the trouble I was having @toxaq. That's why I made this fork to solve the problem for others.

**Comment by pbassut** [comment]
This makes sense. I'll submit a pr tomorrow for this.

**Comment by toxaq** [comment]
There's a comment by @WilliamKoza here https://github.com/ocombe/ocLazyLoad/issues/155 that mentions moving the taRegisterTool to textAngularSetup. Could that be a cleaner solution? I've only had a quick scan of the code so I may be completely off base.

**Comment by pbassut** [comment]
But I think that the idea of who originally did this was to set apart the build of the editor(toolbar, buttons, etc) from the editor itself(functionality, button building, etc). The benefits could be: we could creat lots of textAngularSetup.js to demonstrate different behaviors and features of TA

**Comment by pbassut** [comment]
And sorry, I didn't realize I was commenting on a PR. 
I'm on my phone.

**Comment by garhbod** [comment]
If they need to be separate then taRegisterTool needs to move to setup

**Comment by toxaq** [comment]
@pbassut Yeah, that idea makes sense, it's just the implementation is cart before horse, calling something that isn't a dependency.  Maybe it just needs to be decided which is logically dependent on what, it obviously can't be both dependent on each other.

**Comment by pbassut** [comment]
Yeah. You guys are right. 
Let me have a look tomorrow and we discuss what to do about this?

**Comment by toxaq** [comment]
Sounds great. Thanks @pbassut & @garhbod

**Comment by garhbod** [comment]
Moved taRegisterTool across successfully

**Comment by Program-Monkey** [comment]
when i use it  ,console log a mistake ,i want ask for help .  thanks~  : )   i use the latest version both ocLazyLoad and textAngular . the mistake is: [$injector:unpr] Unknown provider: taRegisterToolProvider <- taRegisterTool  

this is my oclazyloadConfig code:
    {
        name:"textAngular",
        serie: true,
        files:[
            "Scripts/textAngular/dist/textAngular.css",
            "Scripts/textAngular/dist/textAngular-rangy.min.js",
            "Scripts/textAngular/dist/textAngular-sanitize.min.js",
            "Scripts/textAngular/dist/textAngular.min.js"
        ]
    }
the route resolve code:
loadText:["$ocLazyLoad",function($ocLazyLoad){
                return $ocLazyLoad.load("textAngular");
            }]
thank you

**Comment by d4guru** [comment]
I also got here via the ocLazyLoader [issue](https://github.com/fraywing/textAngular/issues/942). For me it is working using textangular.js but not using textangular.min.js . As **@toxaq**  asked why textangular.min.js is not a min version of textangular.js ?

**Pull request merged**
