### PR TITLE
Fix(main): tests weren't running without requireJS

### LINKED ISSUE #871: textAngular.min.js error: ReferenceError: Can't find variable: require at .../textAngular/dist/textAngular.min.js
Getting this error when using textAngular.min.js. If I switch to using textAngular.js and textAngularSetup.js I don't get this error.

Richard B DesLonde@WIN-QOT7FJU27QQ /c/Projects/SportLynxFrontEnd (master)
$ grunt watch
>> Local Npm module "grunt-contrib-compress" not found. Is it installed?

Running "clean:0" (clean) task
Cleaning build...OK

Running "clean:1" (clean) task

Running "html2js:app" (html2js) task
Successfully converted 23 html templates to js.

Running "html2js:common" (html2js) task
Successfully converted 0 html templates to js.

Running "jshint:src" (jshint) task
>> 62 files lint free.

Running "jshint:test" (jshint) task
>> 13 files lint free.

Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:globals" (jshint) task
>> 0 files linted. Please check your ignored files.

Running "coffeelint:src" (coffeelint) task
>> 0 files lint free.

Running "coffeelint:test" (coffeelint) task
>> 0 files lint free.

Running "coffee:source" (coffee) task

Running "less:build" (less) task
File build/assets/SportLynx-0.0.1.css created: 0 B → 147.7 kB

Running "concat:build_css" (concat) task
File "build/assets/SportLynx-0.0.1.css" created.

Running "copy:build_app_assets" (copy) task
Created 1 directories, copied 8 files

Running "copy:build_vendor_assets" (copy) task
Copied 10 files

Running "copy:build_fonts" (copy) task
Copied 5 files

Running "copy:build_appjs" (copy) task
Copied 62 files

Running "copy:build_vendorjs" (copy) task
Copied 24 files

Running "ngAnnotate:build" (ngAnnotate) task
>> 62 files successfully generated.

Running "index:build" (index) task

Running "karmaconfig:unit" (karmaconfig) task

Running "karma:continuous" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9018/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "c:/Projects/SportLynxFrontEnd/src/**/*.coffee" does not
 match any file.
INFO [PhantomJS 1.9.8 (Windows 7)]: Connected on socket Zb68FbTe75aD2J-m-UK5 wit
h id 36335915
PhantomJS 1.9.8 (Windows 7) AppController isCurrentUrl should pass a dummy test
FAILED
        ReferenceError: Can't find variable: require
            at c:/Projects/SportLynxFrontEnd/vendor/textAngular/dist/textAngular
.min.js:18
            at invoke (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3
965)
            at c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3811
            at forEach (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:
325)
            at createInjector (c:/Projects/SportLynxFrontEnd/vendor/angular/angu
lar.js:3811)
            at workFn (c:/Projects/SportLynxFrontEnd/vendor/angular-mocks/angula
r-mocks.js:2353)
        ReferenceError: Can't find variable: require
            at c:/Projects/SportLynxFrontEnd/vendor/textAngular/dist/textAngular
.min.js:18
            at invoke (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3
965)
            at c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3811
            at forEach (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:
325)
            at createInjector (c:/Projects/SportLynxFrontEnd/vendor/angular/angu
lar.js:3811)
            at workFn (c:/Projects/SportLynxFrontEnd/vendor/angular-mocks/angula
r-mocks.js:2353)
PhantomJS 1.9.8 (Windows 7) Registration should match guardian 1 email FAILED
        ReferenceError: Can't find variable: require
            at c:/Projects/SportLynxFrontEnd/vendor/textAngular/dist/textAngular
.min.js:18
            at invoke (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3
965)
            at c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3811
            at forEach (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:
325)
            at createInjector (c:/Projects/SportLynxFrontEnd/vendor/angular/angu
lar.js:3811)
            at workFn (c:/Projects/SportLynxFrontEnd/vendor/angular-mocks/angula
r-mocks.js:2353)
        ReferenceError: Can't find variable: createController
            at c:/Projects/SportLynxFrontEnd/src/app/registration/registration.s
pec.js:37
PhantomJS 1.9.8 (Windows 7) Registration should not change when guardian 1 email
 changes if it already has a value FAILED
        ReferenceError: Can't find variable: require
            at c:/Projects/SportLynxFrontEnd/vendor/textAngular/dist/textAngular
.min.js:18
            at invoke (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3
965)
            at c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:3811
            at forEach (c:/Projects/SportLynxFrontEnd/vendor/angular/angular.js:
325)
            at createInjector (c:/Projects/SportLynxFrontEnd/vendor/angular/angu
lar.js:3811)
            at workFn (c:/Projects/SportLynxFrontEnd/vendor/angular-mocks/angula
r-mocks.js:2353)
        ReferenceError: Can't find variable: createController
            at c:/Projects/SportLynxFrontEnd/src/app/registration/registration.s
pec.js:49
PhantomJS 1.9.8 (Windows 7): Executed 3 of 3 (3 FAILED) ERROR (0.061 secs / 0.05
6 secs)
Warning: Task "karma:continuous" failed. Use --force to continue.

Aborted due to warnings.

### PR DESCRIPTION
**Pull request by pbassut**
Fixes #871

### CODE REVIEW

**Comment by codydaig** [comment]
Confirmed that this fixes the bug. Thanks @pbassut for jumping on that so quickly. :-D

**Comment by pbassut** [comment]
@codydaig Thank you for reporting that so quickly :P

**Comment by codydaig** [comment]
@pbassut I was wondering why everything was working locally, but failing CI. Finally realized that the error was coming from textAngular and when I looked, you just released .4, and when I reverted back to .3 it worked.

**Comment by pbassut** [comment]
We wouldn't catch that a mile away. Our tests were working fine :)

**Pull request merged**
