### PR TITLE
Fix Pasting issue using Chrome on Android 4.2.2

### PR DESCRIPTION
**Pull request by fgodet**

### CODE REVIEW

**Comment by fgodet** [comment]
Sorry should have use a branch

**Comment by SimeonC** [comment]
Thanks for the PR, only on problem - You need to make the changes in the `lib/taBind.js` file not the `src/textAngular.js` file as we compile the lib files to overwrite the src files. The tests won't run on your code as the coverage task does this as well.

**Comment by fgodet** [comment]
Done, thx!

**Comment by SimeonC** [comment]
In release v1.3.10

**Pull request merged**
