### PR TITLE
fix #644: whitespace on paste

### LINKED ISSUE #644: Line breaks not convert to <p> or <br> when pasted from plain text
Here is some plain text that with line breaks.

qq 20150419162226

When copy and paste into textAngular, we get:

qq 20150419162550

This seems to be very unfriendly, as user expected line breaks are keeped everywhere.

It looks like most editors out there can handle this:

qq 20150419162909
qq 20150419162900
 
Would like know if there is a solution for this. Thanks!

### PR DESCRIPTION
**Pull request by yaldak**
Hi everyone,

All tests have passed.

The objective of this PR is to deal with the whitespace on paste problem. To explain what I mean, try pasting plaintext into the editor and observe this behavior:
- newlines do not become br /s
- space at beginning are stripped
- tabs are not dealt with either

My patch fixes all of the above.
It does not break pre pastes either.

Please try and advise. Thanks!

Yalda Kako
Pavlov Media R&D
ykako@pavlovmedia.com

### CODE REVIEW

**Comment by yaldak** [comment]
Updated to use builder pattern

**Comment by pbassut** [comment]
I couldn't reproduce the spaces being stripped on textAngular.com

**Comment by yaldak** [comment]
I was just able to.

My sample data was a bower.json (It can really be any plain text).

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by yaldak** [comment]
Rephrasing the problem:

On paste from plaintext (i.e. my editor Geany)
- CRLF, CR, and LF are stripped
- multiple spaces at the beginning of a line (delimited by above markers) are consolidated into one space, throwing off formatting

**Comment by pbassut** [comment]
I really wanna understand what you're doing here.
I'm on a Mac(uses CR). So, while copying and pasting a text I typed on my text editor with a lot of CR(by pressing enter), textAngular should strip those, right?

**Comment by yaldak** [comment]
I'm on Linux (LF) and have seen this on Chrome on windows as well (client's
machine).

We were trying to copy and paste paragraphs (and later, other texts) from
plain text and insert them into a textAngular field, hoping to preserve the
indentation and new lines.

Using a regular text area, this is preserved (granted it is not rich text).
On textAngular however, we saw that LF, CRLF, \t's were all stripped on
paste.

I can visualize this on a YouTube video or Google Hangout if you have free
time. I do apologize if this is an intended feature. Thanks for all your
hard work on the product.

**Comment by yaldak** [comment]
Some of my above text was mistaken for a quote by GitHub. Please collapse
quote. Sorry!

**Comment by pbassut** [comment]
I would really like an youtube video of this. If you could provide one, that would be just great!
Can you take the time to make one, please?

**Comment by yaldak** [comment]
Absolutely

**Comment by yaldak** [comment]
http://youtu.be/3Z3iOoQGL0w

**Comment by yaldak** [comment]
If you consider this, let me know so I can try to improve the performance of it (Specifically don't like the .replace  callback)

Thanks for your time!

**Comment by pbassut** [comment]
Okay, that is really really weird!
I can't reproduce the issue in any way. I can't download geany here because I'm in a slow connection.
But I'll certainly do it tomorrow and check if it happens with the editor.
Yes, I would point out the replace callback if I merged this. But I don't wanna waste your time and I must really reproduce this.
Thanks for your time.

**Comment by yaldak** [comment]
Thanks Patrick! In my case it isn't just Geany but also Chrome. On my
clients machine it was Chrome as well but on Win32.

You mentioned Mac earlier. I wouldn't be surprised if that has something to
do with it. I'll give iOS a shot now.

**Comment by yaldak** [comment]
I was able to replicate this on iOS. Using Mobile safari open
textAngular.com and copy a segment of plaintext from another tab (I used
Shakespeare from a hosted .txt)

**Comment by pbassut** [comment]
So, I tested this and with geany the issue proceeds. 
Weird, there must be something with geany that's causing this.
Can you test with another text editor?

**Comment by yaldak** [comment]
It's not just geany, I was able to do it in iOS or Chrome Windows just by
copying from another plaintext browser window.

**Comment by pbassut** [comment]
Alright, I'll test this to see if it fixes the issue and that it doesn't break other things.

**Comment by yaldak** [comment]
Thanks Patrick!
I'll see if I can sneak in an optimized version today.
Really not liking the inline function there.

**Comment by pbassut** [comment]
Oh man, I'm on a really slow connection and I forgot to pull your branch.
Sorry I'll definitely do it tomorrow!

**Comment by pbassut** [comment]
@yaldak Okay, tested it. It works. 
But it isn't possible to merge the branch because it's outdated now.
Could you merge master into your branch?

**Comment by yaldak** [comment]
Sure thing, I will address this by EoB tomorrow

Thank you Patrick for your time.

**Comment by pbassut** [comment]
I thank YOU for you PR. Thanks ;p

**Comment by yaldak** [comment]
My pleasure!

**Comment by pbassut** [comment]
I need to get this merged quickly before your branch gets too outdated and it becomes a merge hell.

**Comment by yaldak** [comment]
Sorry for disappearing off the face of the earth - I will do this now

**Comment by yaldak** [comment]
Please see revised PR. 

My apologies, again.

**Pull request closed without merging**
